#!/bin/bash
sudo apt-get update -y
sudo apt-get install apache2 apache2-utils -y
sudo apt install php7.4-cli -y
sudo apt install libapache2-mod-php -y
sudo apt-get install php-mysqlnd -y
sudo apt install php-mysql -y
sudo apt install php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip -y
sudo apt install mysql-client-core-8.0 -y
cd /var/www/html
sudo rm -R index.html
sudo wget https://wordpress.org/latest.tar.gz
sudo tar -xzvf latest.tar.gz
sudo mv wordpress/* ./
sudo chown -R www-data:www-data /var/www/html
sudo systemctl restart apache2

