#!/bin/bash
sudo apt-get update -y
sudo apt-get install apache2 apache2-utils -y
sudo apt install php7.4-cli -y
sudo apt install libapache2-mod-php -y
sudo apt-get install php-mysqlnd -y
sudo apt install php-mysql -y
sudo apt install php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip -y
sudo apt install mysql-client-core-8.0 -y
cd /var/www/html
sudo rm /var/www/html/index.*
cd
sudo apt install awscli -y
sudo aws s3 sync s3://wordpressbucket00/ /var/www/html/
sudo systemctl restart apache2

